# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_studyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.FileField(upload_to='jobs/', verbose_name='作业文件')),
                ('date', models.DateField(auto_now_add=True, verbose_name='交作业时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Student', verbose_name='学员')),
            ],
        ),
    ]
