# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_jobrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecord',
            name='job',
            field=models.TextField(verbose_name='作业文件'),
        ),
    ]
