# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20191128_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='remarks',
            field=models.TextField(default=0, verbose_name='评语'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='job',
            field=models.TextField(verbose_name='作业内容'),
        ),
    ]
