# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-28 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20191128_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.TextField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='批改时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobrecord',
            name='remarks',
        ),
        migrations.AddField(
            model_name='remarkjobs',
            name='job_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.JobRecord', verbose_name='作业内容'),
        ),
    ]
